name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment only on push to main branch

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/reptrack-backend
            git pull origin main
            npm install --production
            pm2 restart reptrack-backend
            pm2 save
            echo "✅ Deployment completed!"
            pm2 status reptrack-backend
